// we will be using this dummy data,
// don't worry, you can find this data in the git repo 
// you can find the git repo link in the description ;)

export const categories = [
  {
    id: 1,
    title: "Engineering",
  },
  {
    id: 2,
    title: "Technology",
  },
  {
    id: 3,
    title: "Programming",
  },
  {
    id: 4,
    title: "Development",
  },
  {
    id: 5,
    title: "Gaming",
  },
]



export const coffeeItems = [
  {
    id: 1,
    name: 'Mobile Technologies',
    tag1: 'Mobile',
    tag2: 'Technology',
    tag3: 'Apps',
    stacks1: 'Mobile Apps',
    stacks2: 'Android',
    stacks3: 'IOS',
    image: require('../assets/images/coffee1.png'),
    desc: 'Mobile Technologies Club is all about staying updated on the latest mobile app development trends, platforms, and tools.'},
  
  {
    id: 2,
    name: 'IEEE',
    tag1: 'Mobile',
    tag2: 'Technology',
    tag3: 'Apps',
    stacks1: 'Research',
    stacks2: 'Tech',
    stacks3: 'Community',
    image: require('../assets/images/coffee2.png'),
    desc: 'IEEE (Institute of Electrical and Electronics Engineers) is a global community of engineers, scientists, and technology enthusiasts. Join us to network and collaborate on cutting-edge projects.'},
  
  {
    id: 3,
    name: 'CodeChef',
    price: '30.00',
    volume: '100 ml',
    stars: '4.0',
    image: require('../assets/images/coffee3.png'),
    desc: 'The taste of coffee can vary depending on factors such as the type of beans, roast level, brewing method, and the addition of any flavors or sweeteners.'  },
  
  {
    id: 4,
    name: 'Alan Turing Club',
    price: '10.30',
    volume: '80 ml',
    stars: '3.5',
    image: require('../assets/images/coffee4.png'),
    desc: 'The taste of coffee can vary depending on factors such as the type of beans, roast level, brewing method, and the addition of any flavors or sweeteners.'  },
  
  {
    id: 5,
    name: 'Google Developer Student Club',
    price: '23.10',
    volume: '120 ml',
    stars: '4.7',
    image: require('../assets/images/coffee5.png'),
    desc: 'The taste of coffee can vary depending on factors such as the type of beans, roast level, brewing method, and the addition of any flavors or sweeteners.'  },
  {
    id: 6,
    name: 'Association for Computing Machinery (ACM)',
    price: '23.10',
    volume: '120 ml',
    stars: '4.7',
    image: require('../assets/images/coffee5.png'),
    desc: 'The taste of coffee can vary depending on factors such as the type of beans, roast level, brewing method, and the addition of any flavors or sweeteners.' },
  {
    id: 7,
    name: 'Product Development Team (PDT)',
    price: '23.10',
    volume: '120 ml',
    stars: '4.7',
    image: require('../assets/images/coffee5.png'),
    desc: 'The taste of coffee can vary depending on factors such as the type of beans, roast level, brewing method, and the addition of any flavors or sweeteners.' },
  {
    id: 8,
    name: 'Computer Society of India (CSI)',
    price: '23.10',
    volume: '120 ml',
    stars: '4.7',
    image: require('../assets/images/coffee5.png'),
    desc: 'The taste of coffee can vary depending on factors such as the type of beans, roast level, brewing method, and the addition of any flavors or sweeteners.' }, 
  {
    id: 9,
    name: 'Bennett DroneSoc',
    price: '23.10',
    volume: '120 ml',
    stars: '4.7',
    image: require('../assets/images/coffee5.png'),
    desc: 'The taste of coffee can vary depending on factors such as the type of beans, roast level, brewing method, and the addition of any flavors or sweeteners.' }, 
  {
    id: 10,
    name: 'Bennett Institute of AI Studies (BAIS)',
    price: '23.10',
    volume: '120 ml',
    stars: '4.7',
    image: require('../assets/images/coffee5.png'),
    desc: 'The taste of coffee can vary depending on factors such as the type of beans, roast level, brewing method, and the addition of any flavors or sweeteners.' },
  {
    id: 11,
    name: 'Quantum Computing',
    price: '23.10',
    volume: '120 ml',
    stars: '4.7',
    image: require('../assets/images/coffee5.png'),
    desc: 'The taste of coffee can vary depending on factors such as the type of beans, roast level, brewing method, and the addition of any flavors or sweeteners.' },
  {
    id: 12,
    name: 'Devops Club',
    price: '23.10',
    volume: '120 ml',
    stars: '4.7',
    image: require('../assets/images/coffee5.png'),
    desc: 'The taste of coffee can vary depending on factors such as the type of beans, roast level, brewing method, and the addition of any flavors or sweeteners.' },
  {
    id: 13,
    name: 'Full Stack Club',
    price: '23.10',
    volume: '120 ml',
    stars: '4.7',
    image: require('../assets/images/coffee5.png'),
    desc: 'The taste of coffee can vary depending on factors such as the type of beans, roast level, brewing method, and the addition of any flavors or sweeteners.' },
  {
    id: 14,
    name: 'IEEE WIE',
    price: '23.10',
    volume: '120 ml',
    stars: '4.7',
    image: require('../assets/images/coffee5.png'),
    desc: 'The taste of coffee can vary depending on factors such as the type of beans, roast level, brewing method, and the addition of any flavors or sweeteners.' },
  {
    id: 15,
    name: 'Geeks for Geeks BU',
    price: '23.10',
    volume: '120 ml',
    stars: '4.7',
    image: require('../assets/images/coffee5.png'),
    desc: 'The taste of coffee can vary depending on factors such as the type of beans, roast level, brewing method, and the addition of any flavors or sweeteners.' },
  {
    id: 16,
    name: 'Technotix',
    price: '23.10',
    volume: '120 ml',
    stars: '4.7',
    image: require('../assets/images/coffee5.png'),
    desc: 'The taste of coffee can vary depending on factors such as the type of beans, roast level, brewing method, and the addition of any flavors or sweeteners.' },
  {
    id: 17,
    name: 'Indian Blockchain Fraternity',
    price: '23.10',
    volume: '120 ml',
    stars: '4.7',
    image: require('../assets/images/coffee5.png'),
    desc: 'The taste of coffee can vary depending on factors such as the type of beans, roast level, brewing method, and the addition of any flavors or sweeteners.' },
  {
    id: 18,
    name: 'Solace Studio (Gaming)',
    price: '23.10',
    volume: '120 ml',
    stars: '4.7',
    image: require('../assets/images/coffee5.png'),
    desc: 'The taste of coffee can vary depending on factors such as the type of beans, roast level, brewing method, and the addition of any flavors or sweeteners.' },
  {
    id: 19,
    name: 'Ciphers (Cyber Sec)',
    price: '23.10',
    volume: '120 ml',
    stars: '4.7',
    image: require('../assets/images/coffee5.png'),
    desc: 'The taste of coffee can vary depending on factors such as the type of beans, roast level, brewing method, and the addition of any flavors or sweeteners.' },
  {
    id: 20,
    name: 'Robotic Process Automation (RPA)',
    price: '23.10',
    volume: '120 ml',
    stars: '4.7',
    image: require('../assets/images/coffee5.png'),
    desc: 'The taste of coffee can vary depending on factors such as the type of beans, roast level, brewing method, and the addition of any flavors or sweeteners.' },
  {
    id: 21,
    name: 'Data Science',
    price: '23.10',
    volume: '120 ml',
    stars: '4.7',
    image: require('../assets/images/coffee5.png'),
    desc: 'The taste of coffee can vary depending on factors such as the type of beans, roast level, brewing method, and the addition of any flavors or sweeteners.' },
  {
    id: 22,
    name: 'Ciphers (Cyber Sec)',
    price: '23.10',
    volume: '120 ml',
    stars: '4.7',
    image: require('../assets/images/coffee5.png'),
    desc: 'The taste of coffee can vary depending on factors such as the type of beans, roast level, brewing method, and the addition of any flavors or sweeteners.' },
  {
    id: 23,
    name: 'ALTReality (AR/VR)',
    price: '23.10',
    volume: '120 ml',
    stars: '4.7',
    image: require('../assets/images/coffee5.png'),
    desc: 'The taste of coffee can vary depending on factors such as the type of beans, roast level, brewing method, and the addition of any flavors or sweeteners.' },
  {
    id: 24,
    name: 'Quantum Computing',
    price: '23.10',
    volume: '120 ml',
    stars: '4.7',
    image: require('../assets/images/coffee5.png'),
    desc: 'The taste of coffee can vary depending on factors such as the type of beans, roast level, brewing method, and the addition of any flavors or sweeteners.' },

]